# Generated by Django 4.1.4 on 2023-01-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dam_check", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PixUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagefile", models.ImageField(blank=True, upload_to="pix_upload")),
            ],
        ),
        migrations.DeleteModel(
            name="PicUpload",
        ),
    ]
